[repository]
name = "hyprtab"
authors = ["semigarden"]

[hyprtab]
description = "Format window/groupbar titles"
authors = ["semigarden"]
output = "build/hyprtab.so"
build = [
    "cmake -S . -B build",
    "cmake --build build -j"
]
